# Generated by Django 5.1.2 on 2025-04-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_userrating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrating",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="userrating",
            index=models.Index(
                fields=["user", "created_at"], name="authenticat_user_id_ea59c6_idx"
            ),
        ),
    ]
