# Generated by Django 5.1.2 on 2024-12-05 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("query_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("AUDIO", "Audio"),
                            ("IMAGE", "Image"),
                            ("FILE", "File"),
                        ],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("AUDIO", "Audio"),
                            ("IMAGE", "Image"),
                            ("FILE", "File"),
                        ],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                ("query_text", models.TextField(blank=True, null=True)),
                ("response_text", models.TextField(blank=True, null=True)),
                ("query_time", models.DateTimeField(auto_now_add=True)),
                ("response_time", models.DurationField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_searches",
                        to="search.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Search",
                "verbose_name_plural": "User Searches",
                "db_table": "user_searches",
                "ordering": ["-query_time"],
                "permissions": [("can_view_all_searches", "Can view all searches")],
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "created_at"], name="search_chat_user_id_ef10f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["is_active", "created_at"],
                name="search_chat_is_acti_c902ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="search",
            index=models.Index(
                fields=["user", "query_time"], name="user_search_user_id_4cbf35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="search",
            index=models.Index(
                fields=["session", "query_time"], name="user_search_session_5e4ef1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="search",
            constraint=models.CheckConstraint(
                condition=models.Q(("query_time__isnull", False)),
                name="query_time_present",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="search",
            unique_together={("user", "query_text")},
        ),
    ]
