# Generated by Django 5.1.2 on 2024-12-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="average_response_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="total_interaction_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="search",
            name="error_occurred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="search",
            name="token_input_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="search",
            name="token_output_count",
            field=models.IntegerField(default=0),
        ),
    ]
